use_frameworks!

platform :ios, '8.0'

target 'WKWebViewJavascriptBridge-BBTCurrentVersionHandler_Example' do
  pod 'WKWebViewJavascriptBridge-BBTCurrentVersionHandler', :path => '../'

  target 'WKWebViewJavascriptBridge-BBTCurrentVersionHandler_Tests' do
    inherit! :search_paths

    
  end
end
