use_frameworks!

platform :ios, '8.0'

target 'WebViewJavascriptBridge-BBTCurrentVersionHandler_Example' do
  pod 'WebViewJavascriptBridge-BBTCurrentVersionHandler', :path => '../'

  target 'WebViewJavascriptBridge-BBTCurrentVersionHandler_Tests' do
    inherit! :search_paths

    
  end
end
